### PR TITLE
Reorganize a bit the project

### PR DESCRIPTION
**Pull request by VincentFoulon80**
Hello,

I wanted to help a little bit and not knowing what to do, I started by reorganizing a bit the project, hope that helps.

Here's my changelog:

# 🔧 Changes

- Add include directive into cargo.toml (so when you do cargo publish only the specified files are sent into crates.io, thus not bloating dependent projects with unnecessary files)
- Reorganize images in a separate directory (and updates README and the html file accordingly) (btw should we move this html file in the docs folder ?)
- Include examples so we can try the crate by using `cargo run --example [example-name]`

### CODE REVIEW

**Comment by HipyCas** [comment]
First of all, thank you so much for contributing! I really like the ideas you present here and I'd like to merge them for sure. A couple of things before merging:

- I would add a bit of documentation to the examples (and I guess you have tried to run them and everything worked as expected).
- Also regarding the examples, importing `Function` is no longer required, as I rewrote the `func!` macro so `Function` doesn't have to be imported.
- Update (at least) the `Cargo.toml` file to the latest version, as the version and other fields have changed.
- About the `html` file, hehe it shouldn't even exist, it was a silly test I did with the README, so you can just go and delete it.

And about everything else it's perfect (you actually included some ideas that I wanted to do). Thank you very much and hope you contribute more!

**Comment by VincentFoulon80** [comment]
You're welcome 🙂 

I've rebased on your last changes and applied your suggestions, I also added a small section for running these example into the README.md

**Comment by HipyCas** [comment]
Everything looks great! I'm merging it!

**Comment by HipyCas** [comment]
Also regarding how you can help, there are a handful of ways! If you want to contribute with code, you can look the Roadmap section in the README and try getting some of it to work, maybe coding the x-axis legend or adding a step to any of the axis legends are also good options (although they are not in the README). Documentation, ideas, or more examples are also welcome!

**Pull request merged**
